name: Build and Push Containers

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build and push images
        run: |
          for dir in containers/*; do
            image=$(basename "$dir")
            docker build -t ghcr.io/${{ github.repository_owner }}/$image "$dir"
            docker push ghcr.io/${{ github.repository_owner }}/$image
          done

